config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'welcome#index'

  resources :users
  resources :articles, except: [:edit, :update] do
    resources :translations, except: :index
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  has_many :translations
  has_many :users, through: :translations, dependent: :destroy

  accepts_nested_attributes_for :translations
end

app/models/translation.rb
# frozen_string_literal: true

class Translation < ApplicationRecord
  belongs_to :user
  belongs_to :article

  validates :question, presence: true
  validates :answer, presence: true
  validates :language, presence: true

  after_destroy :destroy_empty_article

  enum status: %i[draft published]

  AVAILABLE_TRANSLATIONS = [
    ["Arabic", "ar"],
    ["Chinese (Simplified)", "zh"],
    ["Chinese (Traditional)", "zh-TW"],
    ["Czech", "cs"],
    ["Danish", "da"],
    ["Dutch", "nl"],
    ["English", "en"],
    ["Finnish", "fi"],
    ["French", "fr"],
    ["German", "de"],
    ["Hebrew", "he"],
    ["Indonesian", "id"],
    ["Italian", "it"],
    ["Japanese", "ja"],
    ["Korean", "ko"],
    ["Polish", "pl"],
    ["Portuguese", "pt"],
    ["Russian", "ru"],
    ["Spanish", "es"],
    ["Swedish", "sv"],
    ["Turkish", "tr"]
  ]

  def destroy_empty_article
    article.destroy if article.translations.empty?
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :translations
  has_many :articles, through: :translations, dependent: :destroy

  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :destroy]

  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.new
    @article.translations.build
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article, notice: "Article was successfully created."
    else
      render :new
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_url, notice: "Article was successfully destroyed."
  end

  private

    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:id, translations_attributes: [:id, :user_id, :question, :answer, :language])
    end
end

app/controllers/translations_controller.rb
# frozen_string_literal: true

class TranslationsController < ApplicationController
  before_action :set_article
  before_action :set_translation, except: [:new, :create]

  def show
  end

  def new
    @translation = Translation.new
  end

  def edit
  end

  def create
    @translation = @article.translations.build(translation_params)
    return create_automatic_translation if automatic_translation?
    if @translation.save
      redirect_to @article, notice: "Translation was successfully created."
    else
      render :new
    end
  end

  def update
    if @translation.update(translation_params)
      redirect_to article_translation_path(@translation.article, @translation), notice: "Translation was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @translation.destroy
    article = Article.find_by_id(params[:article_id])
    if article
      redirect_to article, notice: "Translation was successfully destroyed."
    else
      redirect_to articles_path, notice: "Translation and Article were successfully destroyed."
    end
  end


  private

    def translation_params
      params.require(:translation).permit(:id, :question, :answer, :user_id, :language, :status)
    end

    def set_translation
      @translation = Translation.find(params[:id])
    end

    def set_article
      @article = Article.find(params[:article_id])
    end

    def automatic_translation?
      params[:automatic_translation] == "1"
    end

    def create_automatic_translation
      TranslatorWorker.perform_async(
        translation_id: @article.translations.first.id,
        user_id: params[:translation][:user_id],
        target_language: params[:translation][:language]
      )
      redirect_to @article, notice: "Automatic translation will be available for review shortly."
    end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to(@user, notice: "User was successfully created.")
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to(@user, notice: "User was successfully updated.")
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: "User was successfully destroyed."
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:email, :name, :surname)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/translation_helper.rb
# frozen_string_literal: true

module TranslationHelper
  def language_flag(language)
    language = language_mapping(language)
    render_flag(language)
  end

  private

    def language_mapping(language)
      return "us" if language == "en"
      return "cn" if language == "zh" || language == "zh-TW"
      language
    end

    def render_flag(language)
      ISO3166::Country[language].emoji_flag
    end
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.fields_for :translations do |translations_form| %>
    <div class="form-group">
      <%= translations_form.label :question %>
      <%= translations_form.text_field :question, { required: true, class: 'form-control' } %>
    </div>

    <div class="form-group">
      <%= translations_form.label :answer %>
      <%= translations_form.text_area :answer, { required: true, class: 'form-control' } %>
    </div>
    <div class="form-group">
      <%= translations_form.label :user %>
      <%= translations_form.select("user_id", User.all.collect {|p| [ p.name, p.id ] }, {prompt: 'Select User'}, { required: true, class: 'form-control' }) %>
    </div>
    <div class="form-group">
      <%= translations_form.label :language %>
      <%= translations_form.select(:language, Translation::AVAILABLE_TRANSLATIONS, {prompt: 'Select Language'}, { required: true, class: 'form-control' }) %>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit class: 'btn btn-sm btn-success' %>
  </div>
<% end %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>
<table class="table table-striped ">
  <thead>
    <%= link_to '+ New Article', new_article_path, class: 'btn btn-success btn-sm pull-right' %>
    <tr>
      <th>Article</th>
      <th>View Translations</th>
      <th>Destroy Article</th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.id %></td>
        <td>
          <%= link_to article, class:"btn btn-sm btn-primary" do %>
            <i class="far fa-user"></i> Show
          <% end %>
        </td>
        <td>
          <%= link_to article, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-sm btn-danger" do %>
            <i class="far fa-trash-alt"></i> Destroy
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<br>
<%= link_to articles_path, class:"btn btn-sm btn-dark" do %>
  <i class="fas fa-undo"></i> Back
<% end %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <ul>
    <% @article.translations.each do |translation| %>
      <li><%= link_to(language_flag(translation.language), article_translation_path(@article, translation), class: 'country-flag') %></li>
    <% end %>
    <li><%= link_to '+ New Translation', new_article_translation_path(@article), class: 'btn btn-success btn-sm' %></li>
  </ul>
</div>
<br>
<%= link_to articles_path, class:"btn btn-sm btn-dark" do %>
  <i class="fas fa-undo"></i> Back
<% end %>

app/views/layouts/application.html.erb
<!Doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">

    <title>MultiQA</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="/">MultiQA</a>
      <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="navbar-collapse collapse" id="navbarsExampleDefault" style="">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <%= link_to 'Users', users_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Articles', articles_path, class: 'nav-link' %>
          </li>
        </ul>
      </div>
    </nav>

    <div class="container">
      <%= yield %>
      <hr>
      <footer>
        <p>&copy; 2019 Jan Zaydowicz</p>
      </footer>
    </div><!-- /.container -->
  </body>
</html>

app/views/translations/_form.html.erb
<%= form_with(model: [@article, translation], local: true) do |form| %>
  <% if translation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(translation.errors.count, "error") %> prohibited this translation from being saved:</h2>

      <ul>
      <% translation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if translation.id.nil? %>
    <%= label_tag(:automatic_translation, "Automatic translation") %>
    <%= check_box_tag(:automatic_translation) %>
  <% end %>

  <div class="form-group manuell-translation">
    <%= form.label :question %>
    <%= form.text_field :question, class: 'form-control' %>
  </div>
  <div class="form-group manuell-translation">
    <%= form.label :answer %>
    <%= form.text_area :answer, class: 'form-control' %>
  </div>
  <div class="form-row">
    <div class="form-group col-md-6">
      <%= form.label :user %>
      <%= form.select("user_id", User.all.collect {|p| [ p.name, p.id ] }, {prompt: 'Select User'}, { required: true, class: 'form-control' }) %>
    </div>
    <div class="form-group col-md-6">
      <%= form.label :language %>
      <%= form.select(:language, Translation::AVAILABLE_TRANSLATIONS, {prompt: 'Select Language'}, { required: true, class: 'form-control' }) %>
    </div>
  </div>
  <div class="form-group manuell-translation">
    <%= form.label :status %>
    <%= form.select :status, Translation.statuses.keys, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= form.submit class: 'btn btn-sm btn-success' %>
  </div>
<% end %>

app/views/translations/edit.html.erb
<h1>Editing Translation</h1>


<%= render 'form', translation: @translation %>

<br>
<div class="btn-group" role="group" aria-label="Basic example">
  <%= link_to article_path(@article), class:"btn btn-sm btn-dark" do %>
  <i class="fas fa-undo"></i> Back
  <% end %>
  <%= link_to article_translation_path(@translation.article, @translation), class:"btn btn-sm btn-primary" do %>
  <i class="fas fa-globe"></i> Show
  <% end %>
</div>

app/views/translations/new.html.erb
<h1>New Translation</h1>

<%= render 'form', translation: @translation %>

<br>
<%= link_to article_path(@article), class:"btn btn-sm btn-dark" do %>
  <i class="fas fa-undo"></i> Back
<% end %>

app/views/translations/show.html.erb
<p id="notice"><%= notice %></p>
<p><%= @translation.question %></p>
<p><%= @translation.answer %></p>
<p class="country-flag"><%= language_flag(@translation.language) %></p>
<p><%= @translation.status %></p>

<br>
<div class="btn-group" role="group" aria-label="Basic example">
  <%= link_to article_path(@translation.article), class:"btn btn-sm btn-dark" do %>
    <i class="fas fa-undo"></i> Back
  <% end %>
  <%= link_to edit_article_translation_path(@translation.article, @translation), class:"btn btn-sm btn-warning" do %>
    <i class="fas fa-edit"></i> Edit
  <% end %>
  <%= link_to article_translation_path(@translation.article, @translation), method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-sm btn-danger" do %>
    <i class="far fa-trash-alt"></i> Destroy
  <% end %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.email_field :email, type:'email', required: true, placeholder: "email@example.com", class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, required: true, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :surname %>
    <%= form.text_field :surname, required: true, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-sm btn-success' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<br>
<div class="btn-group" role="group" aria-label="Basic example">
  <%= link_to users_path, class:"btn btn-sm btn-dark" do %>
  <i class="fas fa-undo"></i> Back
  <% end %>
  <%= link_to @user, class:"btn btn-sm btn-primary" do %>
  <i class="far fa-user"></i> Show
  <% end %>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table class="table table-striped">
  <thead>
    <%= link_to '+ New User', new_user_path, class: 'btn btn-success btn-sm pull-right' %>
    <tr>
      <th>Username</th>
      <th>View Profile</th>
      <th>Edit Profile</th>
      <th>Destroy Profile</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td>
          <%= link_to user, class:"btn btn-sm btn-primary" do %>
            <i class="far fa-user"></i> Show
          <% end %>
        </td>
        <td>
          <%= link_to edit_user_path(user), class:"btn btn-sm btn-warning" do %>
            <i class="fas fa-edit"></i> Edit
          <% end %>
        </td>
        <td>
          <%= link_to user, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-sm btn-danger" do %>
            <i class="far fa-trash-alt"></i> Destroy
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>
<br>
<%= link_to users_path, class:"btn btn-sm btn-dark" do %>
  <i class="fas fa-undo"></i> Back
<% end %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<p><%= @user.name %></p>
<p><%= @user.surname %></p>
<p><%= @user.email %></p>

<h3>Translations</h3>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Question</th>
      <th>Article</th>
      <th>Language</th>
    </tr>
  </thead>
  <tbody>
    <% @user.translations.each do |translation| %>
    <tr>
      <td><%= translation.question  %></td>
      <td><%= link_to translation.article.id, translation.article %></td>
      <td><%= link_to(language_flag(translation.language), article_translation_path(translation.article, translation), class: 'country-flag') %></td>
    </tr>
    <% end %>
  <tbody>
</table>

<br>
<div class="btn-group" role="group" aria-label="Basic example">
  <%= link_to users_path, class:"btn btn-sm btn-dark" do %>
    <i class="fas fa-undo"></i> Back
  <% end %>
  <%= link_to edit_user_path(@user), class:"btn btn-sm btn-warning" do %>
    <i class="fas fa-edit"></i> Edit
  <% end %>
</div>

app/views/welcome/index.html.erb
<div class="starter-template">
  <h1>MultiQA</h1>
  <p class="lead">a state of the art multilingual Q&A tool system with automatic translation support.</p>
</div>